### PR TITLE
Added posibility to test multiple addresses with multiple generated addresses, plus some minor fixes

### PR DESCRIPTION
**Pull request by madacol**
I hope the commits are self-explaining, and thank's for doing this!

BTW just want to state that this works to recover samourai wallets with segwit P2SH addresses (3...), for anyone reading this!

### CODE REVIEW

**Comment by madacol** [comment]
Hey, I managed to make this work on btcrecover https://github.com/gurnec/btcrecover/pull/302 :+1:

**Comment by jonathancross** [comment]
Hey @madacol This is great! Sorry I didn't see this earlier -- somehow didn't get notified.
I just need to test, but code changes look good so far.

Please squash into a single commit.  Thanks!

**Comment by madacol** [comment]
Done!

**Comment by jonathancross** [comment]
Looks great, thanks!

**Pull request merged**
